my_project/ekart/addresses/urls.py
from django.urls import path
from .views import (create_address,adding_selection,AddressList,AddressDetail,AddressCreate,AddressUpdate)

urlpatterns=[
    path("",create_address,name="create"),
    path("attach/",adding_selection,name="attach"),
    path("list/",AddressList.as_view(),name="list"),
    path("<int:pk>/",AddressDetail.as_view(),name = "detail"),
    path("create/", AddressCreate.as_view(),name= "create_add"),
    path("update/<int:pk>/", AddressUpdate.as_view(), name = "update")
]

my_project/ekart/carts/urls.py
from django.urls import path
from .views import update_cart,cart_home

urlpatterns = [
    path("",cart_home,name="home"),
    path("update/", update_cart, name="update"),
]

my_project/ekart/ekart/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.views import register_page,login_page,logout_page
from .views import home_page,home_page1,home_page2,home_page3,about_page,contact_us
from django.conf.urls.static import static
from django.conf import settings 

# . mean accses folder

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_page,name="home"),
    #path("home1/",home_page1),
    path("home2/",home_page2),
    path("home3/",home_page3),
    path("bdy",about_page,name="about"),
    path("bddy",contact_us,name="contact"),
    path("register/",register_page,name="register"),
    path("login/",login_page,name="login"),
    path("logout/",logout_page,name="logout"),
    #include take 2 parameter
    #1 tuple filename url ,app name
    #2 namespace nickname to app here we use product we can use anything
    path("product/",include(('products.urls','products'),namespace='product')),
    path("cart/", include(('carts.urls', 'carts'), namespace="cart")),
    path("order/",include(('orders.urls','orders'),namespace="order")), 
    path("address/",include(("addresses.urls",'addresses'),namespace="address")),

]

urlpatterns=urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns=urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

my_project/ekart/addresses/models.py
from django.db import models
from billing.models import BillingProfile
from django.urls import reverse

# Create your models here.

class AddressQuerySet(models.query.QuerySet):
    def user_address(self,request):
        return self.filter(billing_profile__user__username__iexact=request.user.username)

class AddressManager(models.Manager):
    def get_queryset(self):
        return AddressQuerySet(self.model,using=self._db)
    def get_user_address(self,request):
        return self.get_queryset().user_address(request)     

class Address(models.Model):
    billing_profile=models.ForeignKey(BillingProfile,on_delete=models.CASCADE)
    address_to=models.CharField(max_length=200)
    address_line_1=models.CharField(max_length=120)
    address_line_2=models.CharField(max_length=120)
    city=models.CharField(max_length=120)
    state=models.CharField(max_length=120)
    country=models.CharField(max_length=120,default="India")
    pin_code=models.IntegerField()

    objects=AddressManager()
    
    def __str__(self):
        return self.address_to + ":" + self.address_line_1

    def get_address(self):
        address=self.address_to + "\n" + self.address_line_1 +",\n" + self.address_line_2 +", \n"+self.city+", \n"+self.state+", \n"+self.country+" - " +str(self.pin_code) 
        return address  

    def get_absolute_url(self):
        return reverse("address:detail",kwargs={'pk':self.id})

    def get_update_url(self):
        return reverse("address:update",kwargs={'pk':self.id})
        

my_project/ekart/addresses/forms.py
from django import forms
from .models import Address


class AddressForm(forms.ModelForm):
    class Meta:
        model=Address
        fields=['address_to','address_line_1','address_line_2','city','state','country','pin_code']
        widgets={
            'address_to':forms.TextInput(attrs={'class':"form-control",'value':'Mr./Ms.'}),
            'address_line_1':forms.TextInput(attrs={'class':"form-control"}),
            'address_line_2':forms.TextInput(attrs={'class':"form-control"}),
            'city':forms.TextInput(attrs={'class':"form-control"}),
            'state':forms.TextInput(attrs={'class':"form-control"}),
            'country':forms.TextInput(attrs={'class':"form-control"}),
            'pin_code':forms.NumberInput(attrs={'class':"form-control"}),

        }

my_project/ekart/addresses/views.py
from django.shortcuts import render,redirect
from django.utils.http import is_safe_url
from .forms import AddressForm
from .models import Address
from billing.models import BillingProfile
from carts.models import Cart
from orders.models import Order
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView, UpdateView

# model, fields - modelname_form.html

class AddressUpdate(UpdateView):
    model = Address
    form_class = AddressForm


class AddressCreate(CreateView):
    model = Address
    #fields=['address_to','address_line_1','address_line_2','city','state','country','pin_code']
    form_class = AddressForm

    def post(self, *args, **kwargs):
        form = AddressForm(self.request.POST)
        if form.is_valid():
            add_obj=form.save(commit=False)
            add_obj.billing_profile=BillingProfile.objects.get_or_new(self.request)
            add_obj.save()
            return redirect(add_obj.get_absolute_url())
        return render(self.request, "addresses/address_form.html", {'form':form})



class AddressDetail(DetailView):
    model=Address
    template_name="addresses/detail.html"


class AddressList(ListView):
    model=Address
    template_name="addresses/list.html"

    def get_context_data(self, *args, **kwargs):
        context={'object_list': Address.objects.get_user_address(self.request)}
        return context

def create_address(request):
    redirect_url=request.POST.get('red_url') or None
    addressForm=AddressForm(request.POST or None)
    if addressForm.is_valid():
        add_obj=addressForm.save(commit=False)
        add_obj.billing_profile=BillingProfile.objects.get_or_new(request)
        add_obj.save()
        attach_address(request,add_obj)
        if redirect_url:
            if is_safe_url(redirect_url,request.get_host()):
                return redirect(redirect_url)
    return redirect("home")          

def adding_selection(request):
    redirect_url=request.POST.get('red_url') or None
    addid=request.POST.get("add_detail")
    add_obj=Address.objects.filter(id=addid)
    attach_address(request,add_obj)
    if redirect_url:
        if is_safe_url(redirect_url,request.get_host()):
            return redirect(redirect_url)
    return redirect("home")



def attach_address(request,add_obj):
    cart_obj=Cart.objects.new_or_get(request)
    order_obj=Order.objects.new_or_get(add_obj.billing_profile,cart_obj)
    order_obj.address=add_obj
    order_obj.save()        


# Create your views here.

my_project/ekart/addresses/templates/addresses/address_form.html
{% extends 'layout/layout.html' %}
{% block main %}
    <div class="container">
    	<!-- write enctype when the form uploads an image or a file-->
    	<form method = "POST" enctype = "multipart/form-data">
    	{% csrf_token %}
    	{{form.as_table}}
    	<input type="submit" value="Save" class="btn btn-success"/>
    	</form>
    </div>
{% endblock %}

my_project/ekart/addresses/templates/addresses/detail.html
{% extends 'layout/layout.html' %}
{% block main %}
	<div class = "container">

		<h4>{{object.id}}</h4>
		<h4>{{object.get_address|linebreaks}}</h4>
		<br/>
		<a href = "{{object.get_update_url}}" class = "btn btn-primary">Update</a>
		<a href = "#" class = "btn btn-warning">Delete</a>

	</div>
{% endblock %}

my_project/ekart/addresses/templates/addresses/list.html
{% extends 'layout/layout.html' %}
{% block main %}
    <div class="container">
    <table class="table">
        <tr>
            <td><a href="{% url 'address:create_add' %}" class="btn btn-primary">Add new address</a></td></tr>

         {% for add in object_list %}   
            <tr>
                <td><a href ="{{add.get_absolute_url}}">{{add.get_address|linebreaks}}</a></td>
            </tr>
         {% endfor %}   

    </table>
</div>
{% endblock %}

my_project/ekart/addresses/templates/addresses/selectAddress.html
<from method="POST" action="{% url 'address:attach' %}">

    {% csrf_token %}
    {% for add in addList %}
        <input type="radio" name="add_detail" value="{{add.id}}">{{add.get_address|linebreaks}}</br>
    {% endfor %}    
    <input type="hidden" name="red_url" value="{{request.build_absolute_uri}}"/>
    <input type="submit" value="Select Address" class="btn btn-secondary" />
</form>