my_project/ekart/carts/urls.py
from django.urls import path
from .views import update_cart,cart_home

urlpatterns = [
    path("",cart_home,name="home"),
    path("update/", update_cart, name="update"),
]

my_project/ekart/ekart/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.views import register_page,login_page,logout_page
from .views import home_page,home_page1,home_page2,home_page3,about_page,contact_us
from django.conf.urls.static import static
from django.conf import settings 

# . mean accses folder

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_page,name="home"),
    #path("home1/",home_page1),
    path("home2/",home_page2),
    path("home3/",home_page3),
    path("bdy",about_page,name="about"),
    path("bddy",contact_us,name="contact"),
    path("register/",register_page,name="register"),
    path("login/",login_page,name="login"),
    path("logout/",logout_page,name="logout"),
    #include take 2 parameter
    #1 tuple filename url ,app name
    #2 namespace nickname to app here we use product we can use anything
    path("product/",include(('products.urls','products'),namespace='product')),
    path("cart/", include(('carts.urls', 'carts'), namespace="cart")),
    path("order/",include(('orders.urls','orders'),namespace="order")), 
    path("address/",include(("addresses.urls",'addresses'),namespace="address")),

]

urlpatterns=urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns=urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

my_project/ekart/products/urls.py
from django.urls import path
from .views import ProductListView,ProductDetailView
urlpatterns = [

    path("",ProductListView.as_view(),name="list"),
    #path("<int:pk>",ProductDetailView.as_view(),name="detail")

    path("<str:slug>",ProductDetailView.as_view(),name="detail")
]   

my_project/ekart/templates/layout/css.html
<!-- Bootstrap CSS -->
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<!--add my own css -->

<link rel="stylesheet" href="{% static 'css/main.css' %}">


<link rel="stylesheet" href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

my_project/ekart/templates/layout/footer.html
<div class="alert alert-primary" role="alert">
   Copyrights registerd with Django Batch 2020.
  </div>

my_project/ekart/templates/layout/header.html
{% load static %}
<header>
    <style>
        img {
          
         
          padding: 5px;
          width: 150px;
        }
        </style>

    <table class="table">
        <tr>
            <td>
              <img src="{% static 'img/logo.png'%}">  
            </td>
            <td>
                <h1 style="color:red"><header>Ekart Pvt.Ltd.</h1>
              </td>    
        </tr>    
    </table>    
</header>    

</header>

my_project/ekart/templates/layout/js.html
 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

my_project/ekart/templates/layout/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <title>ekart's pri.ltd.</title>
  </head>
  <body>
        {% include 'layout/css.html' %}
        {% include 'layout/js.html' %}
        {% include 'layout/header.html' %}
        {% include 'layout/menu.html' %}
        {% block main %}
        {% endblock %}
        {% include 'layout/footer.html' %}
</body>
</html>

my_project/ekart/templates/layout/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">About Us</a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'product:list' %}">Products</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:home' %}">
              <i class="fa fa-shopping-cart"></i>
              <span><sup>{{request.session.cart_count}}</sup></span>
            </a>
          </li> 


      {% if not request.user.is_authenticated %}    
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>  

        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>

        {% else %}
          <li class="nav-item dropdown">
          <a class="btn btn-danger dropdown-toggle"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          welcome {{request.user.first_name}} {{request.user.last_name}}
          </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <a class="dropdown-item" href="{%  url 'address:list' %}">Your Addresses</a>
            <!--<a class="dropdown-item" href="#">Another action</a>-->
            
             <div class="dropdown-divider"></div>
            <a class ="dropdown-item" href="{% url 'logout' %}">Logout</a>
            </div>

          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>   
          {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  <br>