my_project/ekart/carts/urls.py
from django.urls import path
from .views import update_cart,cart_home

urlpatterns = [
    path("",cart_home,name="home"),
    path("update/", update_cart, name="update"),
]

my_project/ekart/ekart/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.views import register_page,login_page,logout_page
from .views import home_page,home_page1,home_page2,home_page3,about_page,contact_us
from django.conf.urls.static import static
from django.conf import settings 

# . mean accses folder

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_page,name="home"),
    #path("home1/",home_page1),
    path("home2/",home_page2),
    path("home3/",home_page3),
    path("bdy",about_page,name="about"),
    path("bddy",contact_us,name="contact"),
    path("register/",register_page,name="register"),
    path("login/",login_page,name="login"),
    path("logout/",logout_page,name="logout"),
    #include take 2 parameter
    #1 tuple filename url ,app name
    #2 namespace nickname to app here we use product we can use anything
    path("product/",include(('products.urls','products'),namespace='product')),
    path("cart/", include(('carts.urls', 'carts'), namespace="cart")),
    path("order/",include(('orders.urls','orders'),namespace="order")), 
    path("address/",include(("addresses.urls",'addresses'),namespace="address")),

]

urlpatterns=urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns=urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

my_project/ekart/orders/urls.py
from django.urls import path
from .views import create_order,success

urlpatterns = [

    path("",create_order,name="create"),
    path("success",success,name="success"),    
]

my_project/ekart/carts/models.py
from django.db import models
from products.models import Product
#from django.contrib.auth.models import User
from django.db.models.signals import m2m_changed
from decimal import Decimal
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

# Relationship    1 to 1 , 1 to M , M to M

class CartManager(models.Manager):
    def new_or_get(self, request):
        cartid = request.session.get('cart_id' or None)
        # When cartid is available in session
        if cartid:
            cart_obj = Cart.objects.filter(id=cartid, active=True).first()
        # if cart id is not available in session but a user has a cartid assigned to him or her then load that
        elif request.user.is_authenticated:
            cart_obj = Cart.objects.filter(user=request.user, active=True).first() or None
            if cart_obj is None:
                cart_obj = Cart.objects.create(user=request.user)
            request.session['cart_id'] = cart_obj.id
        # user not logged in nor there is cart id in session
        else:
            cart_obj = Cart.objects.create()
            request.session['cart_id'] = cart_obj.id
        request.session['cart_count'] = cart_obj.products.all().count()
        return cart_obj    

class Cart(models.Model):
    products=models.ManyToManyField(Product,blank=True)

    #CASCADE=delete the requred records
    #protect =dont delete the record
    user=models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE)
    active=models.BooleanField(default=True)
    sub_total=models.DecimalField(max_digits=7,decimal_places=2,default=0)
    total=models.DecimalField(max_digits=7,decimal_places=2,default=0)
    createdDate=models.DateField(auto_now_add=True)
    updatedDate=models.DateField(auto_now=True)

    objects=CartManager()

    def __str__(self):
        return str(self.id)
def m2m_changed_product_receiver(sender,instance,*args,**kwargs):
    if instance.products.all().count()>0:
        instance.sub_total=0
        for prod in instance.products.all():
            instance.sub_total+=prod.price       
        if instance.sub_total< Decimal(500):
            instance.total=instance.sub_total+Decimal(80)
        else:
            instance.total=instance.sub_total
        instance.save()
m2m_changed.connect(m2m_changed_product_receiver,sender=Cart.products.through)                    

my_project/ekart/carts/views.py
from django.shortcuts import render, redirect
from products.models import Product
from .models import Cart

def cart_home(request):
    cart_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {'object':cart_obj})

def update_cart(request):
    # User click on Add to Cart
    # 1. create a cart object and store cart id in session
    # 2. load the product object
    # 3. Cart object I will either add or remove the product
    if request.method == "POST":
        prodid = request.POST.get('prodid')
        prod_obj = Product.objects.filter(id=prodid).first()
        #check for cart_id in session
        # if request.session.get("cart_id"):
        #     cart_obj = Cart.objects.filter(id=request.session.get("cart_id")).first()
        #     print(cart_obj)
        # else:
        #     cart_obj = Cart.objects.create()
        #     request.session['cart_id'] = cart_obj.id
        cart_obj = Cart.objects.new_or_get(request)
        
        if prod_obj in cart_obj.products.all():
            cart_obj.products.remove(prod_obj)
        else:
            cart_obj.products.add(prod_obj)
    # return redirect(prod_obj.get_detailview_url())
    return redirect("cart:home")

my_project/ekart/carts/templates/carts/home.html
{% extends 'layout/layout.html' %}
{% block main %}
    <div class="container">
        {% if object.products.all %}
        <table class="table">
            <tr>
                   <th>Product Name</th>
                   <th></th>
                   <th>Price</th>
            </tr> 
            
            {% for prod in object.products.all %}
            <tr>
                <td>{{prod.title}}</td>
                <td>{% include 'products/snippets/addtocart.html' with object=prod incart=True %}</td>
                <td>{{prod.price}}</td>


            </tr>    
            {% endfor %}

            <tr>
                    <td></td>
                    <td><b>Sub-total</b></td> 
                    <td>{{object.sub_total}}</td>   
             </tr>   

             
            <tr>
                <td></td>
                <td><b>Total</b></td> 
                <td>{{object.total}}</td>   
         </tr> 

            <tr>
                <td></td>
                <td></td>
                <td><form method="POST" action="{% url 'order:create' %}">
                    {% csrf_token %}
                    <input type="submit" value="Place Order" class="btn btn-primary"></form>
                </td>

            </tr>   


         </table>
         {% else %}
            <h1>Cart is Empty</h1>
         {% endif %}   
    </div>   

{% endblock %}