my_project/ekart/carts/urls.py
from django.urls import path
from .views import update_cart,cart_home

urlpatterns = [
    path("",cart_home,name="home"),
    path("update/", update_cart, name="update"),
]

my_project/ekart/ekart/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.views import register_page,login_page,logout_page
from .views import home_page,home_page1,home_page2,home_page3,about_page,contact_us
from django.conf.urls.static import static
from django.conf import settings 

# . mean accses folder

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home_page,name="home"),
    #path("home1/",home_page1),
    path("home2/",home_page2),
    path("home3/",home_page3),
    path("bdy",about_page,name="about"),
    path("bddy",contact_us,name="contact"),
    path("register/",register_page,name="register"),
    path("login/",login_page,name="login"),
    path("logout/",logout_page,name="logout"),
    #include take 2 parameter
    #1 tuple filename url ,app name
    #2 namespace nickname to app here we use product we can use anything
    path("product/",include(('products.urls','products'),namespace='product')),
    path("cart/", include(('carts.urls', 'carts'), namespace="cart")),
    path("order/",include(('orders.urls','orders'),namespace="order")), 
    path("address/",include(("addresses.urls",'addresses'),namespace="address")),

]

urlpatterns=urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns=urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

my_project/ekart/orders/urls.py
from django.urls import path
from .views import create_order,success

urlpatterns = [

    path("",create_order,name="create"),
    path("success",success,name="success"),    
]

my_project/ekart/orders/models.py
from django.db import models
from carts.models import Cart
from billing.models import BillingProfile
from decimal import Decimal
from django.db.models.signals import pre_save
from products.utils import unique_orderid_generator
from addresses.forms import Address

# Create your models here.

ORDER_STATUS_CHOICES=(
    #('stored in db,'Viewed Form'')
    ('created','Created'),
    ('paid','Paid'),
    ('refunded','Refunded'),
    ('shipped','Shipped'),
    ('delivered','Delivered'),
    ('cancel','Cancel'),

)

class OrderManager(models.Manager):
    def new_or_get(self,bill_obj,cart_obj):
        order_obj=self.get_queryset().filter(cart=cart_obj,billingProfile=bill_obj,status="created").first() or None
        if order_obj is None:
            order_obj=self.get_queryset().create(cart=cart_obj,billingProfile=bill_obj)
        order_obj.update_total(cart_obj.total)
        return order_obj    



class Order(models.Model):
    order_id=models.CharField(max_length=120,blank=True,null=True,unique=True)
    #billing profile--FK--Every User will have one billing proifle --Rozar pay--customer Id from RP
    #address--FK(ForeignKey)

    billingProfile=models.ForeignKey(BillingProfile,on_delete=models.PROTECT)
    
    address=models.ForeignKey(Address,null=True,blank=True,on_delete=models.CASCADE)

    cart=models.ForeignKey(Cart,on_delete=models.PROTECT) 

    #enum is RDBMS choice in ORM
    status=models.CharField(default="created",max_length=25,choices=ORDER_STATUS_CHOICES)

    #cart Total
    order_total=models.DecimalField(max_digits=8,decimal_places=2,default=0)

    #Rozer pay ---transactoin id rozerpay_id
    razorpay_id = models.CharField(max_length = 120, null = True, blank = True)

    objects=OrderManager()
    
    def __str__(self):
        return self.order_id


    def update_total(self,cart_total):
        if self.order_total!=cart_total:
            self.order_total=cart_total
            
            self.total=round(self.order_total*Decimal(1.18),2)
            self.save()    

def order_orderid_pre_save_receiver(sender,instance,*args,**kwargs):
    if instance.order_id == "" or instance.order_id is None:
        instance.order_id=unique_orderid_generator(instance)
pre_save.connect(order_orderid_pre_save_receiver,sender=Order)                  

my_project/ekart/orders/views.py
from django.shortcuts import render
from carts.models import Cart
from billing.models import BillingProfile
from .models import Order
from accounts.forms import LoginForm
from addresses.forms import AddressForm
from addresses.models import Address


def success(request):
    pay_id = request.POST.get("razorpay_payment_id")
    orderid = request.POST.get("orderid")
    cart_obj = Cart.objects.new_or_get(request)
    cart_obj.active = False
    # cart_obj - active = True/False
    cart_obj.save()
    # get order_obj
    order_obj = Order.objects.filter(order_id = orderid).first()
    # order_obj - status - paid
    order_obj.status = "paid"
    #order_obj add 
    order_obj.razorpay_id = pay_id
    order_obj.save()
    # delete cart from session
    del request.session['cart_id']
    context = {'oid':orderid, 'pid':pay_id}
    return render(request, "orders/success.html", context)

def create_order(request):
    login_form=LoginForm()
    address_form=AddressForm()
    cart_obj = Cart.objects.new_or_get(request)
    context = {'cart_obj' : cart_obj,'login_form':login_form,'address_form':address_form}
    if request.user.is_authenticated:
        bill_obj = BillingProfile.objects.get_or_new(request)
        context['bill_obj'] = bill_obj
        add_list=Address.objects.filter(billing_profile=bill_obj)
        if add_list.count() > 0:
            context['add_list']=add_list
        order_obj = Order.objects.new_or_get(bill_obj, cart_obj)
        context['order_obj']=order_obj
        print("From orders/views.py : create_order: ", order_obj)
    return render(request, "orders/placeorder.html", context)

my_project/ekart/orders/templates/orders/paynow.html
{% load static %}
<form action="{% url 'order:success' %}" method="POST"> 
    {% csrf_token %}
   <script
   src="https://checkout.razorpay.com/v1/checkout.js"
   data-key="rzp_test_jmQVtMY6NhppaP"
   data-amount="100" 
   data-currency="INR"
   data-buttontext="Pay Now"
   data-name="Ekart Pvt, Lmt."
   data-description="Online Payment transaction"
   data-image="{% static 'img/logo.png'}"
   data-prefill.name="{{obj.billingProfile.user.full_name}}"
   data-prefill.email="{{obj.billingProfile.email}}"
   data-prefill.contact="{{obj.billingProfile.user.mobile}}"
   data-theme.color="#F37254">
   data-notes.shopping_order_id = "{{ obj.order_id }}"</script>
   <input type="hidden" custom="Hidden Element" name="orderid" value = "{{obj.order_id}}">
</form>

my_project/ekart/orders/templates/orders/placeorder.html
{% extends 'layout/layout.html' %}
{% block main %}
    <div class="container">
    {% if order_obj %}
        <h4>Order Id : {{order_obj.order_id}}</h4>
        <h4>Sub Total : {{order_obj.order_total}}</h4>
        <h4>Total : {{order_obj.total}}</h4>
        {% if order_obj.address %}
            <h6>
            {{order_obj.address.get_address | linebreaks}}
            </h6>
            {% include 'orders/paynow.html' with obj=order_obj %}
        {% else %}
        <div class="row"><div class="col-6">
            <form method="POST" action="{% url 'address:create' %}">
                {% csrf_token %}
                {{address_form}}
                <input type="hidden" name="red_url" value="{{request.build_absolute_uri}}"/>
                <input type="submit" value="Add Address" class="btn btn-secondary" />
            </form></div>
        <div class="col-6">
            <h4>Select from Existing Address :</h4>
            {% include 'addresses/selectAddress.html' with addList=add_list %}
        </div></div>
        {% endif %}
    {% else %}
        <div class="col-6">
        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            {{login_form.as_p}}
            <input type="hidden" name="red_url" value="{{request.build_absolute_uri}}"/>
            <input type="submit" value="Submit" class="btn btn-primary" />
        </form>
        </div>
    {% endif %}
    </div>
{% endblock %}

my_project/ekart/orders/templates/orders/success.html
{% extends 'layout/layout.html' %}
{% block main %}

    <div class = "container">
        <h2>Payment Successful</h2>
        <h4> Thank You for Shopping with us.</h4>
        <p>Order Number : {{oid}}</p>
        <p>Payment Transaction Number : {{pid}}</p>
    </div>

{% endblock %}